language: swift
osx_image: xcode11
cache:
  directories:
    - Carthage
    - $HOME/.npm

install: true

before_install:
  - brew install carthage || true
  - brew install swiftlint || true
  - gem update fastlane --no-document

before_script:
  - bash bootstrap.sh --ci

script:
  - set -o pipefail
  - fastlane ios test
