name: Build

on: 
  push:
    branches:
      - development
      - beta
  pull_request:

defaults:
  runs-on: macOS-13
  env:
    XCODE_VERSION: "14.3.1"
  steps:
    - name: Select XCode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - name: Run bootstrap script
      run: ./bootstrap.sh --ci

jobs:
  test:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'CI/skip')) }}
    name: Run tests

    steps:
      - name: Run tests
        run: |
          set -o pipefail
          fastlane ios test

  test_latest_os:
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'CI/latest_os'
    name: Run tests on the latest available iOS simulator
    steps:
      - name: Run latest OS tests
        run: |
          set -o pipefail
          fastlane ios test use_latest_os:true