name: Build

on: 
  push:
    branches:
      - development
      - beta
  pull_request:

jobs:
  test:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'CI/skip')) }}
    name: Run tests
    runs-on: macOS-12
    env:
        # The XCode version to use. If you want to update it please refer to this document:
        # https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-software
        # and set proper version.
        XCODE_VERSION: "13.3.1"

    steps:
      - name: Select XCode
        # Use XCODE_VERSION env variable to set the XCode version you want.
        run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Run bootstrap script
        run: ./bootstrap.sh --ci
      - name: Run tests
        run: |
          set -o pipefail
          fastlane ios test
